name: Generate Structurizr diagrams and publish to GitHub Pages

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'    
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: '>=1.22.0'

      - name: Install Go dependencies
        run: |
          go install github.com/SAP/cloud-mta/mta@latest

      - name: Run Go MTA processor
        run: |
          go version
          // sets the path to the MTA project.
          mf, _ := ioutil.ReadFile("./mta.yaml")
          // Returns an MTA object.
          if err != nil {
            return err
          }
          // unmarshal MTA content.
          m := Unmarshal(mf)
          if err != nil {
            return err
          }
          // Returns the module properties.
          module, err := m.GetModuleByName("eb-java")
          if err != nil {
            return err
          }

      - name: Setup Graphviz
        run: |
          sudo apt-get update
          sudo apt-get install graphviz

      - name: Build model
        run: |
          mvn -q -e -DskipTests package
          mvn -q -e exec:java

      - name: Install Structurizr CLI
        run: |
          curl -L -o structurizr-cli.zip https://github.com/structurizr/cli/releases/download/v2025.11.09/structurizr-cli.zip
          unzip -q structurizr-cli.zip -d structurizr-cli

      - name: Export diagrams
        run: |
          mkdir -p site
          
          #./structurizr-cli/structurizr.sh export -workspace ./dsl/workspace.dsl -format static -output site
          ./structurizr-cli/structurizr.sh export -workspace workspace.json -format static -output site
          #./structurizr-cli/structurizr.sh export -workspace workspace.json -format svg -output site/assets

      - name: Build index page
        run: |
          #echo "# Structurizr Deployment View" > site/index.md
          #echo "![LiveDeployment.svg](assets/LiveDeployment.svg)" >> site/index.md

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: site

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
